<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Code_NT106.Q14._2_Lab02_24521213</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Bai02.Tests\**" />
    <EmbeddedResource Remove="Bai02.Tests\**" />
    <None Remove="Bai02.Tests\**" />
  </ItemGroup>

</Project>